#!/usr/bin/env php

<?php

use League\Container\Container;
use Sunlazor\BlondFramework\Console\Kernel;

define('BASE_PATH', dirname(__FILE__));

include_once BASE_PATH . '/vendor/autoload.php';

/** @var Container $container */
$container = require_once BASE_PATH . '/config/services.php';

/** @var Kernel $kernel */
$kernel = $container->get(Kernel::class);

$status = $kernel->handle();

exit($status);