version: "3.9"
services:
  roadrunner:
    working_dir: "/srv/www"
    build:
      dockerfile: ./docker/roadrunner.yaml
    ports:
      - "8080:8080"
    container_name: "rr"
    volumes:
      - type: bind
        source: ./
        target: /srv/www