version: "3.9"
services:
  roadrunner:
#    working_dir: "/srv/www"
    build:
      dockerfile: ./docker/roadrunner/Dockerfile
    ports:
      - "8080:8080"
    container_name: "rr"
    volumes:
      - ./:/srv/www
#      - project:/srv/www

#    - type: bind
#      source: ./
#      target: /srv/www

#volumes:
#  project: